employee.message=Employee service running
employee.max-records=100
employee.department=IT

spring.datasource.url=jdbc:mysql://localhost:3306/necdb
spring.datasource.username=root
spring.datasource.password=#Sneha4unme
